# Generated by Django 6.0.1 on 2026-02-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone',models.IntegerField(max_length=13, null=True)),
                ('joined_date',models.DateField(auto_now=True, auto_now_add=True))

            ],
        ),
    ]
