# Generated by Django 6.0.2 on 2026-02-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_member_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("last_modifed", models.DateTimeField(auto_now_add=True)),
                ("img", models.ImageField(upload_to="Image")),
            ],
        ),
    ]
