# Generated by Django 6.0.2 on 2026-02-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_formmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formmodel",
            old_name="last_modifed",
            new_name="last_modified",
        ),
        migrations.AlterField(
            model_name="formmodel",
            name="img",
            field=models.ImageField(upload_to="Images/"),
        ),
    ]
